[target.thumbv7em-none-eabihf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[alias]
b = ["build", "--release", "--target", "thumbv7em-none-eabihf"]
bd = ["build", "--target", "thumbv7em-none-eabihf"]

[build]
target = "thumbv7em-none-eabihf"


